use std::collections::BTreeSet;
use std::env;
use std::path::{Path, PathBuf};
use std::process::Command;

fn strip_unc(path: PathBuf) -> PathBuf {
    // Strip \\?\ UNC prefix that confuses MSVC on Windows
    PathBuf::from(
        path.to_str()
            .unwrap()
            .strip_prefix(r"\\?\")
            .unwrap_or(path.to_str().unwrap()),
    )
}

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let runtime_src = strip_unc(
        manifest_dir
            .join("../../runtime")
            .canonicalize()
            .expect("runtime/ directory not found"),
    );

    let vcpkg_toolchain = runtime_src.join("vcpkg/scripts/buildsystems/vcpkg.cmake");

    let build_dir = out_dir.join("cmake-build");
    std::fs::create_dir_all(&build_dir).unwrap();

    // Configure
    let mut cmake_args = vec![
        runtime_src.to_str().unwrap().to_string(),
        format!("-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY={}", out_dir.display()),
    ];
    if vcpkg_toolchain.exists() {
        cmake_args.push(format!(
            "-DCMAKE_TOOLCHAIN_FILE={}",
            vcpkg_toolchain.display()
        ));
        cmake_args.push(format!("-DVCPKG_MANIFEST_DIR={}", runtime_src.display()));
        // x64-windows-static-md: static Allegro + transitive deps, dynamic CRT
        // (matches Rust's default /MD CRT linkage on MSVC). Produces a
        // single-file cb.exe with no runtime DLL dependencies beyond the
        // standard Windows redistributables.
        if cfg!(target_os = "windows") {
            cmake_args.push("-DVCPKG_TARGET_TRIPLET=x64-windows-static-md".to_string());
        }
    }

    let status = Command::new("cmake")
        .args(&cmake_args)
        .current_dir(&build_dir)
        .status()
        .expect("failed to run cmake — is CMake installed and in PATH?");
    assert!(status.success(), "cmake configure failed");

    // Build
    let status = Command::new("cmake")
        .args(["--build", ".", "--config", "Release"])
        .current_dir(&build_dir)
        .status()
        .expect("cmake build invocation failed");
    assert!(status.success(), "cmake build failed");

    // Link our static library
    println!("cargo:rustc-link-search=native={}", out_dir.display());
    // MSVC puts the lib in a Release/ subdirectory
    println!(
        "cargo:rustc-link-search=native={}",
        out_dir.join("Release").display()
    );
    println!("cargo:rustc-link-lib=static=cb_runtime");

    // Read the transitive link list emitted by runtime/CMakeLists.txt.
    // Multi-config generators (MSVC) produce per-config files; we only ever
    // build Release here. Single-config generators (Ninja) write the
    // un-suffixed name when CMAKE_BUILD_TYPE is empty.
    let link_list_candidates = [
        build_dir.join("cb_runtime_link_libs_Release.txt"),
        build_dir.join("cb_runtime_link_libs_.txt"),
        build_dir.join("cb_runtime_link_libs.txt"),
    ];
    let link_list = link_list_candidates
        .iter()
        .find(|p| p.exists())
        .unwrap_or_else(|| {
            panic!(
                "cb_runtime_link_libs_*.txt not generated by CMake under {}",
                build_dir.display()
            )
        });

    let content = std::fs::read_to_string(link_list).expect("failed to read generated link list");

    let mut seen_dirs = BTreeSet::<String>::new();
    let mut seen_libs = BTreeSet::<String>::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let path = Path::new(line);
        if path.is_absolute() {
            // Absolute path to a .lib produced by CMake's $<TARGET_LINKER_FILE:tgt>.
            if let Some(parent) = path.parent() {
                let dir = parent.display().to_string();
                if seen_dirs.insert(dir.clone()) {
                    println!("cargo:rustc-link-search=native={dir}");
                }
            }
            if let Some(stem) = path.file_stem() {
                let name = stem.to_string_lossy().to_string();
                if seen_libs.insert(name.clone()) {
                    println!("cargo:rustc-link-lib=static={name}");
                }
            }
        } else {
            // Bare library name from INTERFACE_LINK_LIBRARIES (typically a
            // Windows system lib like "opengl32" or "dwmapi"). Strip Unix-style
            // -l prefix and any .lib suffix CMake may have included.
            let name = line.trim_start_matches("-l").trim_end_matches(".lib");
            if !name.is_empty() && seen_libs.insert(name.to_string()) {
                println!("cargo:rustc-link-lib={name}");
            }
        }
    }

    // Rebuild if runtime sources change
    for f in &["catalog.cpp", "gfx.c", "input.c", "cb_runtime.h", "CMakeLists.txt"] {
        println!("cargo:rerun-if-changed={}", runtime_src.join(f).display());
    }
}
