//! `proptest` properties for the parser.
//!
//! These are the eight invariants the parser must hold across arbitrary
//! input (see plan §D.3):
//!
//! - `no_panic_on_arbitrary_utf8` — never panics.
//! - `spans_within_source` — every node span is inside `0..src.len()`.
//! - `arena_invariants` — the arena's `len()` matches the number of nodes
//!   reachable through `NodeId(0..len())` and `span_of` returns a span for
//!   each.
//! - `error_nodes_have_diags` — count of `*::Error` AST nodes is bounded
//!   above by the total number of diagnostics emitted (lexer + parser).
//! - `wellformed_no_diags` — well-formed source generated by
//!   [`safe_source`] parses with zero diagnostics.
//! - `recovery_progress` — non-empty input always produces at least one
//!   program statement OR at least one diagnostic.
//! - `idempotent` — parsing the same well-formed source twice produces
//!   the same pretty-printed output.
//!
//! The `terminates` property listed in plan §D.3 collapses into the
//! `no_panic` test in practice — the proptest runner's per-case timeout
//! already wraps execution.

use cb_frontend::ast::{Arena, CaseArm, Expr, NewKind, Node, NodeId, Stmt, TypeExpr};
use cb_frontend::span::FileId;
use cb_frontend::{LexerOptions, parse, tokenize};
use proptest::prelude::*;

fn is_error_node(n: &Node) -> bool {
    matches!(
        n,
        Node::Expr(Expr::Error) | Node::Stmt(Stmt::Error) | Node::TypeExpr(TypeExpr::Error)
    )
}

fn safe_source() -> impl Strategy<Value = String> {
    // Each element is a guaranteed-well-formed CB statement (no escaping
    // hazards, no edge whitespace tricks). The strategy joins 0..6 of them
    // with no separator — each piece already ends with a newline.
    //
    // A few entries embed `\` line continuations so the
    // `continuation_is_transparent` property has something to exercise.
    let stmt = prop_oneof![
        Just("Print 1\n".to_string()),
        (1u32..1000).prop_map(|n| format!("x = {n}\n")),
        Just("Dim y As Integer\n".to_string()),
        Just("If x > 0 Then\n  Print 1\nEndIf\n".to_string()),
        Just("While x\n  Print 1\nWend\n".to_string()),
        Just("For i = 0 To 10\n  Print i\nNext i\n".to_string()),
        Just("Continue\n".to_string()),
        Just("Return\n".to_string()),
        Just("Break\n".to_string()),
        Just("x = 1 + \\\n    2\n".to_string()),
        Just("y = foo(1, \\\n    2, \\\n    3)\n".to_string()),
    ];
    prop::collection::vec(stmt, 0..6).prop_map(|stmts| stmts.concat())
}

/// Reduce parse output to a stable string for `idempotent`. Walks every
/// node id, emits its variant header + span. Order is deterministic
/// because [`Arena::alloc`] is the only mutation path.
fn pretty(arena: &Arena, program: &[NodeId]) -> String {
    use std::fmt::Write as _;
    let mut out = String::new();
    writeln!(out, "program={}", program.len()).unwrap();
    for (i, &id) in program.iter().enumerate() {
        writeln!(out, "top[{i}]={}", id.0).unwrap();
    }
    for i in 0..arena.len() {
        let id = NodeId(i as u32);
        let sp = arena.span_of(id);
        let header = node_header(&arena[id]);
        writeln!(out, "{i}: {header} @ {}..{}", sp.start, sp.end).unwrap();
        for ch in children_of(&arena[id]) {
            writeln!(out, "    -> {}", ch.0).unwrap();
        }
    }
    out
}

fn node_header(node: &Node) -> &'static str {
    match node {
        Node::Expr(e) => match e {
            Expr::IntLit(_) => "Expr::IntLit",
            Expr::FloatLit(_) => "Expr::FloatLit",
            Expr::BoolLit(_) => "Expr::BoolLit",
            Expr::NullLit => "Expr::NullLit",
            Expr::StrLit { .. } => "Expr::StrLit",
            Expr::Ident { .. } => "Expr::Ident",
            Expr::Unary { .. } => "Expr::Unary",
            Expr::Binary { .. } => "Expr::Binary",
            Expr::Call { .. } => "Expr::Call",
            Expr::Index { .. } => "Expr::Index",
            Expr::Field { .. } => "Expr::Field",
            Expr::Paren { .. } => "Expr::Paren",
            Expr::New(_) => "Expr::New",
            Expr::Error => "Expr::Error",
        },
        Node::Stmt(s) => match s {
            Stmt::Assign { .. } => "Stmt::Assign",
            Stmt::ExprStmt { .. } => "Stmt::ExprStmt",
            Stmt::Dim { .. } => "Stmt::Dim",
            Stmt::Global { .. } => "Stmt::Global",
            Stmt::Const { .. } => "Stmt::Const",
            Stmt::Redim { .. } => "Stmt::Redim",
            Stmt::If { .. } => "Stmt::If",
            Stmt::While { .. } => "Stmt::While",
            Stmt::RepeatForever { .. } => "Stmt::RepeatForever",
            Stmt::RepeatWhile { .. } => "Stmt::RepeatWhile",
            Stmt::For { .. } => "Stmt::For",
            Stmt::ForEach { .. } => "Stmt::ForEach",
            Stmt::Select { .. } => "Stmt::Select",
            Stmt::Function { .. } => "Stmt::Function",
            Stmt::Type { .. } => "Stmt::Type",
            Stmt::Struct { .. } => "Stmt::Struct",
            Stmt::FieldDecl { .. } => "Stmt::FieldDecl",
            Stmt::Return { .. } => "Stmt::Return",
            Stmt::Goto { .. } => "Stmt::Goto",
            Stmt::Label { .. } => "Stmt::Label",
            Stmt::Break { .. } => "Stmt::Break",
            Stmt::Continue => "Stmt::Continue",
            Stmt::End => "Stmt::End",
            Stmt::Include { .. } => "Stmt::Include",
            Stmt::Delete { .. } => "Stmt::Delete",
            Stmt::Error => "Stmt::Error",
        },
        Node::TypeExpr(t) => match t {
            TypeExpr::Primitive { .. } => "TypeExpr::Primitive",
            TypeExpr::Named { .. } => "TypeExpr::Named",
            TypeExpr::Array { .. } => "TypeExpr::Array",
            TypeExpr::FnPtr { .. } => "TypeExpr::FnPtr",
            TypeExpr::Paren { .. } => "TypeExpr::Paren",
            TypeExpr::Error => "TypeExpr::Error",
        },
        Node::Param(_) => "Param",
        Node::CaseArm(c) => match c {
            CaseArm::Case { .. } => "CaseArm::Case",
            CaseArm::Default { .. } => "CaseArm::Default",
        },
    }
}

fn children_of(node: &Node) -> Vec<NodeId> {
    let mut out = Vec::new();
    match node {
        Node::Expr(e) => match e {
            Expr::Unary { operand, .. } => out.push(*operand),
            Expr::Binary { lhs, rhs, .. } => {
                out.push(*lhs);
                out.push(*rhs);
            }
            Expr::Call { callee, args } => {
                out.push(*callee);
                out.extend_from_slice(args);
            }
            Expr::Index { array, indices } => {
                out.push(*array);
                out.extend_from_slice(indices);
            }
            Expr::Field { target, .. } => {
                // FD-004 #12: field name is a bare Span, not a child node.
                out.push(*target);
            }
            Expr::Paren { inner } => out.push(*inner),
            Expr::New(NewKind::Type(t)) => out.push(*t),
            Expr::New(NewKind::Array { elem, dims }) => {
                out.push(*elem);
                out.extend_from_slice(dims);
            }
            _ => {}
        },
        Node::Stmt(s) => match s {
            Stmt::Assign { target, value } => {
                out.push(*target);
                out.push(*value);
            }
            Stmt::ExprStmt { expr } => out.push(*expr),
            Stmt::Dim { ty, init, .. } | Stmt::Global { ty, init, .. } => {
                if let Some(t) = ty {
                    out.push(*t);
                }
                if let Some(i) = init {
                    out.push(*i);
                }
            }
            Stmt::Const { ty, value, .. } => {
                if let Some(t) = ty {
                    out.push(*t);
                }
                out.push(*value);
            }
            Stmt::Redim {
                target,
                elem_ty,
                dims,
            } => {
                out.push(*target);
                out.push(*elem_ty);
                out.extend_from_slice(dims);
            }
            Stmt::If {
                cond,
                then_body,
                elseifs,
                else_body,
                ..
            } => {
                out.push(*cond);
                out.extend_from_slice(then_body);
                for ei in elseifs {
                    out.push(ei.cond);
                    out.extend_from_slice(&ei.body);
                }
                if let Some(eb) = else_body {
                    out.extend_from_slice(eb);
                }
            }
            Stmt::While { cond, body } => {
                out.push(*cond);
                out.extend_from_slice(body);
            }
            Stmt::RepeatForever { body } => out.extend_from_slice(body),
            Stmt::RepeatWhile { body, cond } => {
                out.extend_from_slice(body);
                out.push(*cond);
            }
            Stmt::For {
                var,
                from,
                to,
                step,
                body,
                ..
            } => {
                out.push(*var);
                out.push(*from);
                out.push(*to);
                if let Some(s) = step {
                    out.push(*s);
                }
                out.extend_from_slice(body);
            }
            Stmt::ForEach {
                var, source, body, ..
            } => {
                out.push(*var);
                out.push(*source);
                out.extend_from_slice(body);
            }
            Stmt::Select { scrutinee, arms } => {
                out.push(*scrutinee);
                out.extend_from_slice(arms);
            }
            Stmt::Function {
                params,
                return_ty,
                body,
                ..
            } => {
                out.extend_from_slice(params);
                if let Some(r) = return_ty {
                    out.push(*r);
                }
                out.extend_from_slice(body);
            }
            Stmt::Type { fields, .. } | Stmt::Struct { fields, .. } => {
                out.extend_from_slice(fields);
            }
            Stmt::FieldDecl { ty: Some(t), .. } => {
                out.push(*t);
            }
            Stmt::Return { value: Some(v) } => out.push(*v),
            Stmt::Include { path } => out.push(*path),
            _ => {}
        },
        Node::TypeExpr(t) => match t {
            TypeExpr::Array { elem, .. } => out.push(*elem),
            TypeExpr::FnPtr { params, ret } => {
                out.extend_from_slice(params);
                if let Some(r) = ret {
                    out.push(*r);
                }
            }
            TypeExpr::Paren { inner } => out.push(*inner),
            _ => {}
        },
        Node::Param(p) => {
            if let Some(t) = p.ty {
                out.push(t);
            }
            if let Some(d) = p.default {
                out.push(d);
            }
        }
        Node::CaseArm(c) => match c {
            CaseArm::Case { values, body } => {
                out.extend_from_slice(values);
                out.extend_from_slice(body);
            }
            CaseArm::Default { body } => out.extend_from_slice(body),
        },
    }
    out
}

proptest! {
    /// Parsing arbitrary UTF-8 must never panic.
    #[test]
    fn no_panic_on_arbitrary_utf8(src in any::<String>()) {
        let (tokens, _) = tokenize(&src, FileId(0), LexerOptions::default());
        let _ = parse(&tokens, &src, FileId(0));
    }

    /// Every AST node's span must lie within `0..src.len()`, and
    /// `start <= end`. Parsers occasionally hand out empty spans at EOF
    /// (start == end == src.len()), which is fine.
    #[test]
    fn spans_within_source(src in any::<String>()) {
        let (tokens, _) = tokenize(&src, FileId(0), LexerOptions::default());
        let r = parse(&tokens, &src, FileId(0));
        for i in 0..r.arena.len() {
            let id = NodeId(i as u32);
            let span = r.arena.span_of(id);
            prop_assert!(
                span.start <= span.end,
                "span out of order at id {i}: {}..{}",
                span.start,
                span.end,
            );
            prop_assert!(
                span.end as usize <= src.len(),
                "span past EOF at id {i}: end={}, src.len()={}",
                span.end,
                src.len(),
            );
        }
    }

    /// The arena's `len()` is a non-negative count and `span_of` returns a
    /// valid span for every id in `0..len()`. (`Arena::nodes` and
    /// `Arena::spans` are `pub(crate)`, so this is the strongest invariant
    /// the public API surfaces.)
    #[test]
    fn arena_invariants(src in any::<String>()) {
        let (tokens, _) = tokenize(&src, FileId(0), LexerOptions::default());
        let r = parse(&tokens, &src, FileId(0));
        let len = r.arena.len();
        // Every id in 0..len must be indexable without panicking; the
        // matching span must be retrievable too.
        for i in 0..len {
            let id = NodeId(i as u32);
            let _node = &r.arena[id];
            let _span = r.arena.span_of(id);
        }
        // The program's top-level ids must all be valid arena ids.
        for &id in &r.program {
            prop_assert!((id.0 as usize) < len);
        }
    }

    /// The count of `*::Error` AST nodes is bounded above by the total
    /// number of diagnostics (lexer + parser): every error node was
    /// produced with at least one paired diagnostic.
    #[test]
    fn error_nodes_have_diags(src in any::<String>()) {
        let (tokens, lex_diags) = tokenize(&src, FileId(0), LexerOptions::default());
        let r = parse(&tokens, &src, FileId(0));
        let err_nodes: usize = (0..r.arena.len())
            .filter(|&i| is_error_node(&r.arena[NodeId(i as u32)]))
            .count();
        let total_diags = lex_diags.len() + r.diagnostics.len();
        prop_assert!(
            err_nodes <= total_diags,
            "{} error nodes vs {} diagnostics",
            err_nodes,
            total_diags,
        );
    }

    /// Well-formed source produces zero diagnostics. If this regresses,
    /// either `safe_source` slipped (fix the strategy) or the parser
    /// rejects valid CB (fix the parser).
    #[test]
    fn wellformed_no_diags(src in safe_source()) {
        let (tokens, lex_diags) = tokenize(&src, FileId(0), LexerOptions::default());
        prop_assert!(
            lex_diags.is_empty(),
            "lexer diagnostics on safe source:\n{}\n{:?}",
            src,
            lex_diags,
        );
        let r = parse(&tokens, &src, FileId(0));
        prop_assert!(
            r.diagnostics.is_empty(),
            "parser diagnostics on safe source:\n{}\n{:?}",
            src,
            r.diagnostics,
        );
    }

    /// Input that yields at least one significant (non-Newline, non-Eof)
    /// token must produce at least one program statement OR at least one
    /// diagnostic — the parser never silently throws away real input.
    /// Comment-only and whitespace-only inputs legitimately leave both
    /// empty.
    #[test]
    fn recovery_progress(src in any::<String>()) {
        let (tokens, lex_diags) = tokenize(&src, FileId(0), LexerOptions::default());
        let significant_tokens = tokens
            .iter()
            .filter(|t| !matches!(
                t.kind,
                cb_frontend::TokenKind::Newline | cb_frontend::TokenKind::Eof,
            ))
            .count();
        if significant_tokens == 0 {
            return Ok(());
        }
        let r = parse(&tokens, &src, FileId(0));
        prop_assert!(
            !r.program.is_empty()
                || !r.diagnostics.is_empty()
                || !lex_diags.is_empty(),
            "input with {} significant tokens produced no statements and no diagnostics: {src:?}",
            significant_tokens,
        );
    }

    /// Parsing the same well-formed input twice must yield identical
    /// pretty-prints. Catches accidental nondeterminism (hashing,
    /// thread-local state, etc.).
    #[test]
    fn idempotent(src in safe_source()) {
        let (toks_a, _) = tokenize(&src, FileId(0), LexerOptions::default());
        let r_a = parse(&toks_a, &src, FileId(0));
        let (toks_b, _) = tokenize(&src, FileId(0), LexerOptions::default());
        let r_b = parse(&toks_b, &src, FileId(0));
        prop_assert_eq!(pretty(&r_a.arena, &r_a.program), pretty(&r_b.arena, &r_b.program));
    }

    /// Continuation tokens must be transparent to the parser (FD-004 #1).
    /// Parsing a well-formed source with `preserve_trivia=true` (so
    /// `\` line-continuations survive as `TokenKind::Continuation` tokens
    /// in the stream) must yield the same AST as parsing it with the
    /// default (where the lexer discards the continuation entirely).
    /// Trivia (Whitespace, Comment) is stripped from both runs to isolate
    /// the Continuation question; safe_source does not contain those anyway.
    #[test]
    fn continuation_is_transparent(src in safe_source()) {
        let (toks_default, _) = tokenize(&src, FileId(0), LexerOptions::default());
        let r_default = parse(&toks_default, &src, FileId(0));

        let opts = LexerOptions { preserve_trivia: true };
        let (toks_preserve, _) = tokenize(&src, FileId(0), opts);
        let toks_preserve: Vec<_> = toks_preserve
            .into_iter()
            .filter(|t| !matches!(
                t.kind,
                cb_frontend::TokenKind::Whitespace | cb_frontend::TokenKind::Comment(_),
            ))
            .collect();
        let r_preserve = parse(&toks_preserve, &src, FileId(0));

        prop_assert_eq!(
            pretty(&r_default.arena, &r_default.program),
            pretty(&r_preserve.arena, &r_preserve.program),
        );
    }
}
